
disabled_rules: # Rule identifiers to exclude from running
  #warning
  - file_length
  - line_length
  - cyclomatic_complexity #方法中的条件判断太多不超过10个
  - unneeded_break_in_switch #switch中不必要的break
  - control_statement #if等条件判断不要有括号
  - switch_case_alignment #case要和switch对齐
  - colon #冒号和前面的变量紧挨着
  - vertical_parameter_alignment  #多行变量（形参）要对齐
  - nesting #类型嵌套至多一层
  - type_name #类型名字3-40个字之间
  - syntactic_sugar #使用语法糖-Array<Int> -> [Int]
  - todo #提醒你去做 - low
  - legacy_constructor  #使用swift的构造器
  - function_body_length  #方法内部的行数
  - compiler_protocol_init #low
  - implicit_getter #只读属性不用加get，直接return
  - redundant_string_enum_value #字符串枚举变量名和值不要相等
  - unused_optional_binding # !=nil比let _ = 好
  - function_parameter_count #形参不要大于5个
  - unused_closure_parameter #回调的形参没用到
  - for_where #用for where 不要for if XX==XX
  - fallthrough #不要用这个在switch中 用default或者别的
  - multiple_closures_with_trailing_closure #感觉这个不好避免
  - type_body_length #类的内部代码行数<200
  - operator_whitespace #func ==() 加个空格 - 好改
  - empty_enum_arguments #case .failure( _) 不太好改，和swift编译warning冲突
  - weak_delegate #！delegate 用weak声明
  - large_tuple #返回的元祖最多2个元素  
  # - mark #mark的使用格式不对

  #error
  - identifier_name #！开头小写
  - force_cast #强制转换 as! ，这个超多
  - force_try #强制try
  - shorthand_operator #赋值的时候不建议复杂计算

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

reporter: "html"